title: Enrico Quaglia
description: Testi, idee e creazioni
author: Enrico Quaglia
url: "https://eqenrico-hub.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  testi:
    output: true
    permalink: /testi/:name/
  testi-en:
    output: true
    permalink: /en/texts/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "testi"
    values:
      layout: "testo"
      lang: "it"
  - scope:
      path: ""
      type: "testi-en"
    values:
      layout: "testo-en"
      lang: "en"
  - scope:
      path: "en"
    values:
      lang: "en"
